'use client';

import { useState } from 'react';
import { Download, Maximize2, X } from 'lucide-react';
import type { Artifact } from '@/lib/domain/types';
import { cn, formatBytes } from '@/lib/utils';
import { FileChip } from '@/components/run-card';

const COLS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

function cell(v: string | number) {
  if (typeof v === 'number') return v.toLocaleString('en-US', { maximumFractionDigits: 2 });
  return v;
}

/** Cell-by-cell preview of a generated workbook, or the text of a memo. */
export function SheetPreview({ artifact, onClose }: { artifact: Artifact; onClose?: () => void }) {
  const [tab, setTab] = useState<'Preview' | 'Details'>('Preview');
  const [sheetIdx, setSheetIdx] = useState(0);
  const [wide, setWide] = useState(false);
  const sheet = artifact.sheets?.[sheetIdx];
  const width = Math.max(...(sheet?.rows.map((r) => r.length) ?? [0]), 1);
  const filler = Math.max(0, 24 - (sheet?.rows.length ?? 0));

  return (
    <div className={cn('flex min-h-0 flex-1 flex-col', wide && 'fixed inset-4 z-50 rounded-2xl border border-line bg-white p-4 shadow-lift')}>
      <div className="flex items-center gap-3 pb-3">
        <FileChip kind={artifact.kind} size="md" />
        <span className="min-w-0 flex-1 truncate text-[14px] font-medium text-ink" title={artifact.filename}>
          {artifact.filename}
        </span>
        <a href={artifact.url} download className="rounded-md p-1.5 text-muted hover:bg-neutral-100" aria-label="Download">
          <Download className="h-4 w-4" />
        </a>
        <button type="button" onClick={() => setWide(!wide)} className="rounded-md p-1.5 text-muted hover:bg-neutral-100" aria-label={wide ? 'Shrink' : 'Expand'}>
          {wide ? <X className="h-4 w-4" /> : <Maximize2 className="h-4 w-4" />}
        </button>
        {onClose && !wide && (
          <button type="button" onClick={onClose} className="rounded-md p-1.5 text-muted hover:bg-neutral-100" aria-label="Close preview">
            <X className="h-4 w-4" />
          </button>
        )}
      </div>
      <nav className="mb-3 flex gap-5 border-b border-line">
        {(['Preview', 'Details'] as const).map((t) => (
          <button
            key={t}
            type="button"
            onClick={() => setTab(t)}
            className={cn('-mb-px border-b-2 px-1 pb-2.5 text-[13.5px]', tab === t ? 'border-accent font-medium text-accent' : 'border-transparent text-muted')}
          >
            {t}
          </button>
        ))}
      </nav>

      {tab === 'Details' ? (
        <dl className="space-y-3 text-[13px]">
          {[
            ['File', artifact.filename],
            ['Type', artifact.kind.toUpperCase()],
            ['Size', formatBytes(artifact.sizeBytes)],
            ['Generated by', artifact.generatedBy],
            ['Sheets', artifact.sheets?.map((s) => s.name).join(', ') ?? '—'],
          ].map(([k, v]) => (
            <div key={k} className="flex gap-4">
              <dt className="w-28 shrink-0 text-muted">{k}</dt>
              <dd className="min-w-0 break-words text-ink">{v}</dd>
            </div>
          ))}
        </dl>
      ) : artifact.sheets && sheet ? (
        <>
          {artifact.sheets.length > 1 && (
            <label className="mb-3 flex items-center gap-2 text-[13px] text-muted">
              Sheet:
              <select
                id="sheet-select"
                value={sheetIdx}
                onChange={(e) => setSheetIdx(Number(e.target.value))}
                className="rounded-lg border border-line bg-white px-2 py-1.5 text-[13px] text-ink"
              >
                {artifact.sheets.map((s, i) => (
                  <option key={s.name} value={i}>
                    {s.name}
                  </option>
                ))}
              </select>
            </label>
          )}
          <div className="min-h-0 flex-1 overflow-auto rounded-lg border border-line">
            <table className="border-collapse text-[11.5px]">
              <thead className="sticky top-0 bg-neutral-50">
                <tr>
                  <th className="w-8 border border-line" />
                  {Array.from({ length: width }, (_, i) => (
                    <th key={i} className="min-w-[88px] border border-line px-2 py-1 font-normal text-muted">
                      {COLS[i] ?? i + 1}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {sheet.rows.map((row, r) => (
                  <tr key={r}>
                    <td className="border border-line bg-neutral-50 px-1.5 text-center text-muted">{r + 1}</td>
                    {Array.from({ length: width }, (_, c) => (
                      <td
                        key={c}
                        className={cn(
                          'max-w-[200px] truncate border border-line px-2 py-1.5',
                          r === 0 && 'font-semibold text-ink',
                          typeof row[c] === 'number' && 'text-right tabular-nums',
                        )}
                        title={row[c] === undefined ? undefined : String(row[c])}
                      >
                        {row[c] === undefined ? '' : cell(row[c])}
                      </td>
                    ))}
                  </tr>
                ))}
                {Array.from({ length: filler }, (_, i) => (
                  <tr key={`f${i}`}>
                    <td className="border border-line bg-neutral-50 px-1.5 text-center text-muted">{sheet.rows.length + i + 1}</td>
                    {Array.from({ length: width }, (_, c) => (
                      <td key={c} className="h-[26px] border border-line" />
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {artifact.sheets.length > 1 && (
            <nav className="mt-2 flex gap-1 overflow-x-auto border-t border-line pt-2">
              {artifact.sheets.map((s, i) => (
                <button
                  key={s.name}
                  type="button"
                  onClick={() => setSheetIdx(i)}
                  className={cn('whitespace-nowrap rounded-md px-3 py-1.5 text-[12.5px]', i === sheetIdx ? 'bg-accent-soft font-medium text-accent' : 'text-muted hover:bg-neutral-100')}
                >
                  {s.name}
                </button>
              ))}
            </nav>
          )}
        </>
      ) : artifact.paragraphs ? (
        <div className="min-h-0 flex-1 space-y-3 overflow-y-auto rounded-lg border border-line bg-white p-5 text-[13.5px] leading-relaxed text-ink/85">
          {artifact.paragraphs.map((p, i) =>
            p.startsWith('§ ') ? (
              <h3 key={i} className="pt-2 text-[14.5px] font-semibold text-ink">
                {p.slice(2)}
              </h3>
            ) : (
              <p key={i}>{p}</p>
            ),
          )}
        </div>
      ) : (
        <p className="text-[13px] text-muted">No preview for this file — download it to open.</p>
      )}
    </div>
  );
}
